jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    handlers:
        datetime:
            default_format: 'D M d Y H:i:s eO'

    default_context:
      serialization:
          serialize_null: true
      deserialization:
          serialize_null: true
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
