security:

    role_hierarchy:
        ROLE_VIEWER:
            - ROLE_USER
            - ROLE_PIA_LIST
            - ROLE_PIA_VIEW
            - ROLE_MEASURE_LIST
            - ROLE_MEASURE_VIEW
            - ROLE_EVALUATION_LIST
            - ROLE_EVALUATION_VIEW
            - ROLE_ANSWER_LIST
            - ROLE_ANSWER_VIEW
        ROLE_DPO:
            - ROLE_VIEWER
            - ROLE_PIA_CREATE
            - ROLE_PIA_EDIT
            - ROLE_PIA_DELETE
            - ROLE_MEASURE_DELETE
            - ROLE_EVALUATION_CREATE
            - ROLE_EVALUATION_EDIT
            - ROLE_EVALUATION_DELETE
            - ROLE_ANSWER_DELETE
        ROLE_CONTROLLER:
            - ROLE_VIEWER
            - ROLE_PIA_EDIT
            - ROLE_MEASURE_CREATE
            - ROLE_MEASURE_EDIT
            - ROLE_ANSWER_CREATE
            - ROLE_ANSWER_EDIT
            - ROLE_ANSWER_DELETE
        ROLE_ADMIN:
            - ROLE_DPO
            - ROLE_CONTROLLER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        # oauth_authorize:
        #     pattern:    ^/oauth/v2/auth
        #     form_login:
        #         # login_path: /login
        #         # check_path: /login_check
        #         provider: fos_userbundle
        
        api:
            pattern:    ^/(pias|profile|pia-templates|folders)
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
            anonymous: true
            logout: true

    access_control:
        - { path: ^/login, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/resetting, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
