[template]
src = "apache.example.conf.tmpl"
dest = "config/apache.example.conf"
keys = [
     "/apache/servername",
     "/apache/directory",
     "/apache/certificate/file",
     "/apache/certificate/key",
]
