[template]
src = "apache.example.conf.tmpl"
dest = "apache.example.conf"
keys = [
     "/apache/servername",
     "/apache/directory",
     "/apache/certifcate/file",
     "/apache/certifcate/key",
]
